# Generated by Django 4.2.24 on 2025-09-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("contact_info", models.TextField(blank=True)),
                ("kyc_status", models.CharField(default="PENDING", max_length=20)),
                ("bank_details", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_no", models.CharField(max_length=50, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("seat_map_json", models.TextField(blank=True, default=dict)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buses",
                        to="buses.operator",
                    ),
                ),
            ],
        ),
    ]
