# Generated by Django 4.2.24 on 2026-02-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_ticket_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="state_of_residence",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="whatsapp_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DroppingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("location_name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropping_points",
                        to="bookings.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="BoardingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("location_name", models.CharField(max_length=150)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_points",
                        to="bookings.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="boarding_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.boardingpoint",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="dropping_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.droppingpoint",
            ),
        ),
    ]
