# Generated by Django 5.2.13 on 2026-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0012_operator_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatorsale",
            options={
                "ordering": ["-confirmed_at", "-id"],
                "verbose_name": "Operator sale",
                "verbose_name_plural": "Operator sales",
            },
        ),
        migrations.RenameIndex(
            model_name="schedulelocation",
            new_name="bookings_sc_schedul_ed5598_idx",
            old_name="bookings_sc_schedul_8a0b0d_idx",
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
