# Generated by Django 5.2.13 on 2026-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0014_add_cancellation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
