# Generated by Django 5.2.13 on 2026-04-11 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("schedule_approved", "Schedule approved"),
                            ("schedule_rejected", "Schedule rejected"),
                            ("operator_updated", "Operator updated"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("schedule", "Schedule"), ("operator", "Operator")],
                        max_length=32,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="admin_porta_created_ecf84d_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="admin_porta_target__f06f00_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="admin_porta_action_e40da6_idx",
                    ),
                ],
            },
        ),
    ]
